/lauv_controller:
  ros__parameters:

    # =========================================
    # INNER LOOP: VELOCITY CONTROL (Force/Torque)
    # =========================================
    
    k_p_u: 2.0
    k_i_u: 0.5
    k_d_u: 0.0

    k_p_v: 0.0
    k_i_v: 0.0
    k_d_v: 0.0

    k_p_w: 0.0
    k_i_w: 0.0
    k_d_w: 0.0

    k_p_p: 0.0
    k_i_p: 0.0
    k_d_p: 0.0

    k_p_q: 0.0
    k_i_q: 0.0
    k_d_q: 0.0

    k_p_r: 0.0
    k_i_r: 0.0
    k_d_r: 0.0

    # =========================================
    # OUTER LOOP: POSITION CONTROL (Desired Velocity)
    # =========================================

    k_p_x: 0.0
    k_i_x: 0.0
    k_d_x: 0.0

    k_p_y: 0.0  # All zeros
    k_i_y: 0.0
    k_d_y: 0.0

    k_p_z: 0.0
    k_i_z: 0.0  # Small integral to fix steady-state depth error
    k_d_z: 0.0

    k_p_phi: 0.0 # Keep wings level
    k_i_phi: 0.0
    k_d_phi: 0.0

    k_p_theta: 0.0
    k_i_theta: 0.0
    k_d_theta: 0.0

    k_p_psi: 0.0
    k_i_psi: 0.0
    k_d_psi: 0.0